
default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: toy_app_development


